apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medicare-plus-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ayoubMah/medicare-gitops.git
    targetRevision: week-08
    path: helm-charts/medicare-plus
    helm:
      valueFiles:
        - ../values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: medicare-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
